### PR TITLE
UI: Add ability to un-accept per story

### PR DESCRIPTION
**Pull request by ndelangen**
# What I did:

- I added an extra callback function prop that invokes a mutation changing the status back to pending
- I passed this callback down to the right component
- In the `SnapshotComparison`-component I added an button that is shown when the status is `APPROVED`
- The button invokes the callback when clicked

# How to test

I tried this and it did not work! I need help figuring out why!

- Open the repo storybook
- Make a change that will be detected in chromatic
- Start a build (clicking the button in the sidebar should do it)
- Go to the addon's Panel
- Wait for the change to appear
- Approve the change
- Wait for that to build to be updated
- It should now show the "Unapprove" button <-- This was not working when I was testing this locally
- Clicking the "Unapprove" button should cause the "Approve" button to appear again.

# Open questions:

I suspect that there are scenarios where there's a newer build coming in where "Approve" and "Unapprove" need to be disabled. @tmeasday 

<details>
  <summary>📦 Published PR as canary version: <code>0.0.59--canary.82.de5dbe0.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @chromaui/addon-visual-tests@0.0.59--canary.82.de5dbe0.0
  # or 
  yarn add @chromaui/addon-visual-tests@0.0.59--canary.82.de5dbe0.0
  ```
</details>

### CODE REVIEW

**Review by tmeasday — APPROVED** [review]
LGTM, thanks @ndelangen 

> I suspect that there are scenarios where there's a newer build coming in where "Approve" and "Unapprove" need to be disabled. @tmeasday

Yes, I think it's part of this ticket @ndelangen https://linear.app/chromaui/issue/AP-3633/show-snapshot-outdated-header-as-soon-as-we-have-a-new-snapshot-for.

If you are interested in tackling it, it would be simply when `nextBuild.id !== storyBuild?.id`

**Comment by ndelangen** [comment]
@ghengeveld or @tmeasday did either of you see that I'm blocked here?
When I tested this locally, it did not work.

The "How to test" section states where things break.
I'd appreciate it either of you could advise or assist.

**Comment by ghengeveld** [comment]
It did work for me, it just took a while for the UI to update. I created a ticket for that [here](https://linear.app/chromaui/issue/AP-3637/acceptunaccept-buttons-dont-immediately-update-after-update). Could you try again and see if you get the same effect?

**Comment by ndelangen** [comment]
Yes, I see that too, it took about 5 second for me.

**Pull request merged**
