### PR TITLE
Align with Storybook 8.2 core package layout

### PR DESCRIPTION
**Pull request by ndelangen**
This updates the addon to follow "core package consolidation" changes. Various internal Storybook packages have been moved, so this updates the imports.

<details>
  <summary>📦 Published PR as canary version: <code>1.9.0--canary.330.06b1103.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @chromatic-com/storybook@1.9.0--canary.330.06b1103.0
  # or 
  yarn add @chromatic-com/storybook@1.9.0--canary.330.06b1103.0
  ```
</details>

### CODE REVIEW

**Comment by ndelangen** [comment]
The visual changes picked up seem to be flake. somehow?

When running on my local machine, the tooltips show up.

**Comment by ghengeveld** [comment]
Yeah those hover tooltips are flaky. I've denied and rerun the build. If the new build is the same then I will accept them.

**Comment by ndelangen** [comment]
Do not merge until 8.2 is fully released.

This change would lock us into supporting only 8.2 (unsure if that's what we want to do?)

I opened this mainly to showcase what needs to happen to be CPC "compliant"

**Review by ghengeveld — APPROVED** [review]
Needs to be updated to the actual `^8.2.0` range but other than that this is good.

**Pull request merged**
