### PR TITLE
Show error when build is limited (account is out of snapshots)

### PR DESCRIPTION
**Pull request by ghengeveld**
Rather than hanging the build at the Verify step, fail the build with an error and link to the Billing screen.

I did not bother designing this to be any fancier than the default error message we already had.

Screenshot 2024-03-05 at 10 50 38

Screenshot 2024-03-05 at 10 50 44

<details>
  <summary>📦 Published PR as canary version: <code>1.2.8--canary.194.78d37d8.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @chromatic-com/storybook@1.2.8--canary.194.78d37d8.0
  # or 
  yarn add @chromatic-com/storybook@1.2.8--canary.194.78d37d8.0
  ```
</details>

### CODE REVIEW

**Comment by domyen** [comment]
@MichaelArestad did you have an error state for this?

**Comment by MichaelArestad** [comment]
@domyen Yes. All the error states can be found [here](https://www.figma.com/file/GFEbCgCVDtbZhngULbw2gP/Visual-Tests-addon-for-Storybook?type=design&node-id=7295%3A197066&mode=design&t=70V5ziAA5CaqW0Y5-1). For this use case, these two are the most relevant: 
image

**Comment by andrewortwein** [comment]
Code changes look fine to me, but should we try to implement the error state designs above?

**Comment by domyen** [comment]
I think we should try to implement the error state because it associates the blocker with "upgrading plan".

**Pull request merged**
